version: "3.8"
services:
  backend:
    build:
        context: ./backend
    container_name: librillo_backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    
    volumes:
      - ./backend:/app
      - ./.env:/app/.env 
      - /app/node_modules
    command: ["npm","start"]

  frontend:
    image: nginx:alpine
    container_name: librillo_frontend
    ports:
      - "8080:80"
    volumes:
     - ./frontend:/usr/share/nginx/html

volumes:
  pgdata:
